name: Auto Approve Dependabot PRs

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}
          review-message: "Auto approved automated PR"
