name: Auto Approve and Merge Dependabot PRs

on: pull_request_target

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}
          review-message: "Auto approved automated PR"

      - name: Automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        with:
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}
